Q = { S | C | I | D | SA | RF }

// types
float = { "-"? ~ value ~ "." ~ value? }
string = { "'" ~ (ASCII_ALPHANUMERIC | "_" | "-" | " ")+ ~ "'" }
int = { "-"? ~ value }
bool = { ^"TRUE" | ^"FALSE" }

where_clause = { WHERE ~ whitespace+ ~ field ~ whitespace+ ~ op ~ whitespace+ ~ field_value }
op = { "=" | "!=" | ">=" | "<=" | ">" | "<" }
value = { ASCII_DIGIT+ }
ftype = { ^"BOOL" | ^"STRING" | ^"INT" | ^"FLOAT" }
whitespace = _{ (" " | "\t" | "\n") }
field_value = { float | int | bool | string }

fields_all = { "*" }
fields = { (field ~ whitespace* ~ "," ~ whitespace*)* ~ field }
fields_types = { (field_type ~ whitespace* ~ "," ~ whitespace*)* ~ field_type }
field_value_setters = { ( field_value_setter ~ whitespace* ~ "," ~ whitespace* )* ~ field_value_setter }

key_value = { int | string }

field_value_setter = { field ~ whitespace* ~ "=" ~ whitespace* ~ field_value }
field_type = { field ~ whitespace*~ ":" ~ whitespace* ~ ftype }
field = { ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_" | "-")* }
table = { ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_" | "-")* }

file_path = { ("/" | "\\" | ASCII_ALPHANUMERIC | "-" | "." | "_" | ":" | " ")+ }

SAVE_AS = _{ ^"SAVE_AS" }
READ_FROM = _{ ^"READ_FROM" }
SELECT = _{ ^"SELECT" }
CREATE = _{ ^"CREATE" }
DELETE = _{ ^"DELETE" }
INSERT = _{ ^"INSERT" }
FIELDS = _{ ^"FIELDS" }
INTO = _{ ^"INTO" }
FROM = _{ ^"FROM" }
WHERE = _{ ^"WHERE" }
KEY = _{ ^"KEY" }

S = { SELECT ~ whitespace+ ~ (fields | fields_all) ~ whitespace+ ~ FROM ~ whitespace+ ~ table ~ (whitespace+ ~ where_clause)? }
C = { CREATE ~ whitespace+ ~ table ~ whitespace+ ~ KEY ~ whitespace+ ~ field ~ whitespace+ ~ FIELDS ~ whitespace+ ~ fields_types }
I = { INSERT ~ whitespace+ ~ field_value_setters ~ whitespace+ ~ INTO ~ whitespace+ ~ table }
D = { DELETE ~ whitespace+ ~ key_value ~ whitespace+ ~ FROM ~ whitespace+ ~ table }
SA = { SAVE_AS ~ whitespace+ ~ file_path }
RF = { READ_FROM ~ whitespace+ ~ file_path }
